{"uuid": "2ceb03fa-6033-451f-b05e-43001b3d3636", "children": ["2969b4ff-9025-416d-80e9-0f3fc6ef26ca"], "befores": [{"name": "setup_final", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: window was already closed\n  (Session info: chrome=80.0.3987.163)\n\n", "trace": "  File \"/Users/KIMO/Desktop/Testing/venv/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/KIMO/Desktop/Testing/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 958, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/KIMO/Desktop/Testing/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 784, in call_fixture_func\n    res = next(it)\n  File \"/Users/KIMO/Desktop/Testing/Web_Testing/Tests/test_premium.py\", line 64, in setup_final\n    self.driver.get(WebHelper().get_premium_url())\n  File \"/Users/KIMO/Desktop/Testing/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"/Users/KIMO/Desktop/Testing/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/KIMO/Desktop/Testing/venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1586743707539, "stop": 1586743707544}], "start": 1586743707539, "stop": 1586743707595}