{"uuid": "9e7e823a-563d-434c-92e6-27f79e89a83b", "children": ["e1fe4a15-f446-4a1e-9036-1629502fa465"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: window was already closed\n  (Session info: chrome=80.0.3987.163)\n\n", "trace": "  File \"/Users/KIMO/Desktop/Testing/venv/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/KIMO/Desktop/Testing/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 958, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/KIMO/Desktop/Testing/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 784, in call_fixture_func\n    res = next(it)\n  File \"/Users/KIMO/Desktop/Testing/Web_Testing/Tests/test_premium.py\", line 55, in setup\n    self.driver.get(WebHelper().get_premium_url())\n  File \"/Users/KIMO/Desktop/Testing/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"/Users/KIMO/Desktop/Testing/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/KIMO/Desktop/Testing/venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1586743707315, "stop": 1586743707323}], "start": 1586743707315, "stop": 1586743707358}