{"name": "Login with wrong email", "status": "passed", "description": "Signing in with the following credentials email : kamelmohsenkamel & password: Kimo2010", "attachments": [{"name": "SUCCESS: Login failed with incorrect credentials", "source": "2385a10e-7a0e-4400-accb-7bbab871b5b5-attachment.png", "type": "image/png"}], "start": 1584335682126, "stop": 1584335689808, "uuid": "6557f24d-5336-42fe-a1a0-4d2a340519b6", "historyId": "b9ca19a10222315a5ea05b954dc66a1d", "testCaseId": "ea1582cff99b4a6d96e3e94b3ca92adf", "fullName": "Tests.test_signin.TestLogin#test_case_3", "labels": [{"name": "suite", "value": "Login Tests"}, {"name": "severity", "value": "blocker"}, {"name": "feature", "value": "Log in Tests"}, {"name": "parentSuite", "value": "End to End testing"}, {"name": "story", "value": "Failing login"}, {"name": "subSuite", "value": "Login with wrong email"}, {"name": "tag", "value": "Do"}, {"name": "tag", "value": "Login"}, {"name": "host", "value": "DESKTOP-1RVKD4K"}, {"name": "thread", "value": "19308-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_signin"}]}