{"name": "Login with wrong email", "status": "passed", "description": "Signing in with the following credentials email : kamelmohsenkamel & password: Kimo2010", "attachments": [{"name": "SUCCESS: Login failed with incorrect credentials", "source": "aa684863-49e8-4cab-883b-d64b4fc4a98e-attachment.png", "type": "image/png"}], "start": 1584338330459, "stop": 1584338340310, "uuid": "41e335f9-5b3a-4114-8eef-6b0a47c33de7", "historyId": "b9ca19a10222315a5ea05b954dc66a1d", "testCaseId": "ea1582cff99b4a6d96e3e94b3ca92adf", "fullName": "Tests.test_signin.TestLogin#test_case_3", "labels": [{"name": "suite", "value": "Login Tests"}, {"name": "parentSuite", "value": "End to End testing"}, {"name": "story", "value": "Failing login"}, {"name": "severity", "value": "blocker"}, {"name": "subSuite", "value": "Login with wrong email"}, {"name": "feature", "value": "Log in Tests"}, {"name": "tag", "value": "Login"}, {"name": "tag", "value": "Do"}, {"name": "host", "value": "DESKTOP-1RVKD4K"}, {"name": "thread", "value": "204-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_signin"}]}