{"uuid": "1d7ca014-d542-4932-a111-9a529c62f2ed", "children": ["68b601ad-ef24-48c3-a28b-a12ee6c7a7f4"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=connectionFailure&u=http%3A//localhost%3A3000/signin&c=UTF-8&f=regular&d=Firefox%20can%E2%80%99t%20establish%20a%20connection%20to%20the%20server%20at%20localhost%3A3000.\n\n", "trace": "  File \"C:\\Users\\Mohammad\\Desktop\\University\\Software_Engineering\\projectX\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Mohammad\\Desktop\\University\\Software_Engineering\\projectX\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Mohammad\\Desktop\\University\\Software_Engineering\\projectX\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"C:\\Users\\Mohammad\\Desktop\\University\\Software_Engineering\\projectX\\Web_Testing\\Tests\\test_login.py\", line 24, in setup\n    self.driver.get(self.link)\n  File \"C:\\Users\\Mohammad\\Desktop\\University\\Software_Engineering\\projectX\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"C:\\Users\\Mohammad\\Desktop\\University\\Software_Engineering\\projectX\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Mohammad\\Desktop\\University\\Software_Engineering\\projectX\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1586147756313, "stop": 1586147759049}], "start": 1586147756313, "stop": 1586147759577}