{"name": "Login with wrong password", "status": "passed", "description": "Signing in with the following credentials email : kamelmohsenkamel@gmail.com & password: wrong password", "attachments": [{"name": "test_login_failed_login", "source": "d6ad07bd-d72e-407c-8382-6e55dd886e1a-attachment.png", "type": "image/png"}], "start": 1583923147920, "stop": 1583923150582, "uuid": "84436f6d-cbb9-4c5d-a917-1d44c1a5e5f6", "historyId": "9002a5477b70c2d2732bd4879bd4c9b3", "testCaseId": "5849ff08927baae0bfe7bd1d291d6dac", "fullName": "Tests.login_tests.Test#test_case_2", "labels": [{"name": "severity", "value": "blocker"}, {"name": "parentSuite", "value": "End to End testing"}, {"name": "suite", "value": "Login Tests"}, {"name": "subSuite", "value": "Login with wrong password"}, {"name": "story", "value": "Failing login"}, {"name": "feature", "value": "Log in Tests"}, {"name": "tag", "value": "Do"}, {"name": "tag", "value": "Login"}, {"name": "host", "value": "DESKTOP-1RVKD4K"}, {"name": "thread", "value": "8060-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.login_tests"}]}