{"name": "Login with wrong username", "status": "passed", "description": "Signing in with the following credentials email : kamelmohsenkamel & password: Kimo2010", "attachments": [{"name": "test_login_failed_login", "source": "e34bc09c-18d6-4d18-bb4a-5d1e718eb65a-attachment.png", "type": "image/png"}], "start": 1583924193359, "stop": 1583924195992, "uuid": "5e9904ef-66d4-42f5-9cdf-b5b845d37ccc", "historyId": "9002a5477b70c2d2732bd4879bd4c9b3", "testCaseId": "5849ff08927baae0bfe7bd1d291d6dac", "fullName": "Tests.login_tests.Test#test_case_2", "labels": [{"name": "story", "value": "Failing login"}, {"name": "feature", "value": "Log in Tests"}, {"name": "parentSuite", "value": "End to End testing"}, {"name": "severity", "value": "blocker"}, {"name": "suite", "value": "Login Tests"}, {"name": "subSuite", "value": "Login with wrong username"}, {"name": "tag", "value": "Do"}, {"name": "tag", "value": "Login"}, {"name": "host", "value": "DESKTOP-1RVKD4K"}, {"name": "thread", "value": "13240-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.login_tests"}]}