{"name": "Login with wrong username", "status": "passed", "description": "Signing in with the following credentials email : kamelmohsenkamel & password: Kimo2010", "attachments": [{"name": "test_login_failed_login", "source": "e17625a8-4eb5-4512-b6ee-ba2fbfa9b49e-attachment.png", "type": "image/png"}], "start": 1583924234490, "stop": 1583924237105, "uuid": "6a86a4d3-8687-4b8a-89ef-6e80a3d637b5", "historyId": "9002a5477b70c2d2732bd4879bd4c9b3", "testCaseId": "5849ff08927baae0bfe7bd1d291d6dac", "fullName": "Tests.login_tests.Test#test_case_2", "labels": [{"name": "suite", "value": "Login Tests"}, {"name": "severity", "value": "blocker"}, {"name": "story", "value": "Failing login"}, {"name": "feature", "value": "Log in Tests"}, {"name": "parentSuite", "value": "End to End testing"}, {"name": "subSuite", "value": "Login with wrong username"}, {"name": "tag", "value": "Login"}, {"name": "tag", "value": "Do"}, {"name": "host", "value": "DESKTOP-1RVKD4K"}, {"name": "thread", "value": "8792-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.login_tests"}]}