{"name": "Login with wrong username", "status": "passed", "description": "Signing in with the following credentials email : kamelmohsenkamel & password: Kimo2010", "attachments": [{"name": "test_login_failed_login", "source": "6c3d061d-8183-4437-8429-20d2c6ba92fe-attachment.png", "type": "image/png"}], "start": 1583923969487, "stop": 1583923972087, "uuid": "17631f08-2799-49b3-838d-44f3f4b1aaf1", "historyId": "9002a5477b70c2d2732bd4879bd4c9b3", "testCaseId": "5849ff08927baae0bfe7bd1d291d6dac", "fullName": "Tests.login_tests.Test#test_case_2", "labels": [{"name": "severity", "value": "blocker"}, {"name": "suite", "value": "Login Tests"}, {"name": "feature", "value": "Log in Tests"}, {"name": "parentSuite", "value": "End to End testing"}, {"name": "subSuite", "value": "Login with wrong username"}, {"name": "story", "value": "Failing login"}, {"name": "tag", "value": "Do"}, {"name": "tag", "value": "Login"}, {"name": "host", "value": "DESKTOP-1RVKD4K"}, {"name": "thread", "value": "9916-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.login_tests"}]}