{"name": "Login with wrong password", "status": "passed", "description": "Signing in with the following credentials email : kamelmohsenkamel@gmail.com & password: wrong password", "attachments": [{"name": "test_login_failed_login", "source": "96ae4dd9-cf53-4ea9-a4fe-ba284b7a28b9-attachment.png", "type": "image/png"}], "start": 1583923371799, "stop": 1583923374394, "uuid": "2adefe2c-d7fe-45ce-8d86-429e38d058d6", "historyId": "9002a5477b70c2d2732bd4879bd4c9b3", "testCaseId": "5849ff08927baae0bfe7bd1d291d6dac", "fullName": "Tests.login_tests.Test#test_case_2", "labels": [{"name": "feature", "value": "Log in Tests"}, {"name": "suite", "value": "Login Tests"}, {"name": "parentSuite", "value": "End to End testing"}, {"name": "story", "value": "Failing login"}, {"name": "subSuite", "value": "Login with wrong password"}, {"name": "severity", "value": "blocker"}, {"name": "tag", "value": "Login"}, {"name": "tag", "value": "Do"}, {"name": "host", "value": "DESKTOP-1RVKD4K"}, {"name": "thread", "value": "17384-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.login_tests"}]}